export const EVENTS = {
  GET_TABS: 'GET_TABS',
  SUGGESTIONS_UPDATED: 'SUGGESTIONS_UPDATED',
  REQUEST_SUGGESTIONS: 'REQUEST_SUGGESTIONS',
  REQUEST_NAVIGATION: 'REQUEST_NAVIGATION',
  TOGGLE_PALETTE: 'TOGGLE_PALETTE'
}
